menu:
<<<<<<< HEAD
  主页: /
  档案: /archives
  个人信息:
  相册:

=======
  Home: /
  Archives: /archives
>>>>>>> origin/master

widgets:
- search
- category
- tag

<<<<<<< HEAD
excerpt_link: 阅读全文
=======
excerpt_link: Read More
>>>>>>> origin/master

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light